Revert "libahci: Fix possible Spectre-v1 pmp indexing in ahci_led_store()"
We don't care about spectre-v1 with our igepv2 build

It should fix build:
  ./include/linux/compiler.h:527:45: error: call to '__compiletime_assert_1129' declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long)

This reverts commit 5600d61e7d9521f69bf500744cd6e72dd96d37ba.